# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshCaSignerReleases < Formula
  desc "Interactive CLI tool for signing SSH certificates using AWS Lambda SSH CA"
  homepage "https://github.com/qm-labs/ssh-ca-signer"
  version "2.7.3"
  license "Internal use only - Quantum Machines"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qm-labs/ssh-ca-signer-releases/releases/download/v2.7.3/ssh-ca-signer-releases_2.7.3_Darwin_x86_64.tar.gz"
      sha256 "6337340161bdea844263ed6e500c3c1289dab9e30b180d6778df2251b8c3334d"

      def install
        bin.install "ssh-ca-signer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qm-labs/ssh-ca-signer-releases/releases/download/v2.7.3/ssh-ca-signer-releases_2.7.3_Darwin_arm64.tar.gz"
      sha256 "1286bdc11a4ddad58b0e90802ab74919a7943600766f47e5ef5984473067b7cd"

      def install
        bin.install "ssh-ca-signer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qm-labs/ssh-ca-signer-releases/releases/download/v2.7.3/ssh-ca-signer-releases_2.7.3_Linux_x86_64.tar.gz"
      sha256 "4a79d83bd2d09c44dcea02789e53c2a42109c96bd4f4d7819300617123e20b7c"
      def install
        bin.install "ssh-ca-signer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qm-labs/ssh-ca-signer-releases/releases/download/v2.7.3/ssh-ca-signer-releases_2.7.3_Linux_arm64.tar.gz"
      sha256 "4b6d421216a1bed6da0132e131e6423eaedf3c9074a65194285783d18511e301"
      def install
        bin.install "ssh-ca-signer"
      end
    end
  end

  test do
    system "#{bin}/ssh-ca-signer", "--version"
  end
end
