# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshCaSigner < Formula
  desc "Interactive CLI tool for signing SSH certificates using AWS Lambda SSH CA"
  homepage "https://github.com/qm-labs/ssh-ca-signer"
  version "2.9.0"
  license "Internal use only - Quantum Machines"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qm-labs/ssh-ca-signer-releases/releases/download/v2.9.0/ssh-ca-signer-releases_2.9.0_Darwin_x86_64.tar.gz"
      sha256 "c5ca2497a05c7886537384f9a5ac2bd23b74bd78841a691790985a24f7575198"

      def install
        bin.install "ssh-ca-signer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qm-labs/ssh-ca-signer-releases/releases/download/v2.9.0/ssh-ca-signer-releases_2.9.0_Darwin_arm64.tar.gz"
      sha256 "fa5336f195dada2b58c3203a9e5743e062d35cfd6df750a028a2f561aabd3d9e"

      def install
        bin.install "ssh-ca-signer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qm-labs/ssh-ca-signer-releases/releases/download/v2.9.0/ssh-ca-signer-releases_2.9.0_Linux_x86_64.tar.gz"
      sha256 "1a7365ce3237de0e871639da26191f74a24a6405f514b769b8ebdcef6fffa078"
      def install
        bin.install "ssh-ca-signer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qm-labs/ssh-ca-signer-releases/releases/download/v2.9.0/ssh-ca-signer-releases_2.9.0_Linux_arm64.tar.gz"
      sha256 "85a08d35b0e41f63be0769c5bd0a2bff29595c9015233df2e0f45bde64ff1317"
      def install
        bin.install "ssh-ca-signer"
      end
    end
  end

  test do
    system "#{bin}/ssh-ca-signer", "--version"
  end
end
