# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshCaSigner < Formula
  desc "Interactive CLI tool for signing SSH certificates using AWS Lambda SSH CA"
  homepage "https://github.com/qm-labs/ssh-ca-signer"
  version "2.10.0"
  license "Internal use only - Quantum Machines"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qm-labs/ssh-ca-signer-releases/releases/download/v2.10.0/ssh-ca-signer-releases_2.10.0_Darwin_x86_64.tar.gz"
      sha256 "9238c75e26fed884d108ec27cf17f903ce692a17a18df23767ce6f6a8ed29831"

      def install
        bin.install "ssh-ca-signer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qm-labs/ssh-ca-signer-releases/releases/download/v2.10.0/ssh-ca-signer-releases_2.10.0_Darwin_arm64.tar.gz"
      sha256 "bd5c8ac9ea112cd6991369e43ec2b4c1fec01f552f39fd86d6fb96875104f96c"

      def install
        bin.install "ssh-ca-signer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qm-labs/ssh-ca-signer-releases/releases/download/v2.10.0/ssh-ca-signer-releases_2.10.0_Linux_x86_64.tar.gz"
      sha256 "0d397600a0b4e83cd432a64363dc197a4bdc28b09a78b7da41adb43103a9b7a6"
      def install
        bin.install "ssh-ca-signer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qm-labs/ssh-ca-signer-releases/releases/download/v2.10.0/ssh-ca-signer-releases_2.10.0_Linux_arm64.tar.gz"
      sha256 "8d05017db1cf7fd3113d35e4b8297693451dc11ad1faa6d1a91f692ef6ccc5f3"
      def install
        bin.install "ssh-ca-signer"
      end
    end
  end

  test do
    system "#{bin}/ssh-ca-signer", "--version"
  end
end
